/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';




export namespace Components {

  interface AttachmentsGallery {}
  interface AttachmentsGalleryAttributes extends StencilHTMLAttributes {}

  interface MainContainer {}
  interface MainContainerAttributes extends StencilHTMLAttributes {}
}

declare global {
  interface StencilElementInterfaces {
    'AttachmentsGallery': Components.AttachmentsGallery;
    'MainContainer': Components.MainContainer;
  }

  interface StencilIntrinsicElements {
    'attachments-gallery': Components.AttachmentsGalleryAttributes;
    'main-container': Components.MainContainerAttributes;
  }


  interface HTMLAttachmentsGalleryElement extends Components.AttachmentsGallery, HTMLStencilElement {}
  var HTMLAttachmentsGalleryElement: {
    prototype: HTMLAttachmentsGalleryElement;
    new (): HTMLAttachmentsGalleryElement;
  };

  interface HTMLMainContainerElement extends Components.MainContainer, HTMLStencilElement {}
  var HTMLMainContainerElement: {
    prototype: HTMLMainContainerElement;
    new (): HTMLMainContainerElement;
  };

  interface HTMLElementTagNameMap {
    'attachments-gallery': HTMLAttachmentsGalleryElement
    'main-container': HTMLMainContainerElement
  }

  interface ElementTagNameMap {
    'attachments-gallery': HTMLAttachmentsGalleryElement;
    'main-container': HTMLMainContainerElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
